<?php
/**
* Verifone e-commerce PrestaShop Module
*
* Feel free to contact Verifone e-commerce at support@paybox.com for any
* question.
*
* LICENSE: This source file is subject to the version 3.0 of the Open
* Software License (OSL-3.0) that is available through the world-wide-web
* at the following URI: http://opensource.org/licenses/OSL-3.0. If
* you did not receive a copy of the OSL-3.0 license and are unable
* to obtain it through the web, please send a note to
* support@paybox.com so we can mail you a copy immediately.
*
*  @category  Module / payments_gateways
*  @version   3.0.19
*  @author    BM Services <contact@bm-services.com>
*  @copyright 2012-2017 Verifone e-commerce
*  @license   http://opensource.org/licenses/OSL-3.0
*  @link      http://www.paybox.com/
*/

if (!defined('_PS_VERSION_')) {
    exit;
}

/**
 * ISO 3166 Country class.
 *
 * @class   PayboxIso3166Country
 */
class PayboxIso3166Country
{
    /**
     * Mapping of country ISO 3166 alpha code & numeric code
     *
     * @var array
     */
    private static $_mapping = [
        'AD' => '020',
        'AE' => '784',
        'AF' => '004',
        'AG' => '028',
        'AI' => '660',
        'AL' => '008',
        'AM' => '051',
        'AO' => '024',
        'AQ' => '010',
        'AR' => '032',
        'AS' => '016',
        'AT' => '040',
        'AU' => '036',
        'AW' => '533',
        'AX' => '248',
        'AZ' => '031',
        'BA' => '070',
        'BB' => '052',
        'BD' => '050',
        'BE' => '056',
        'BF' => '854',
        'BG' => '100',
        'BH' => '048',
        'BI' => '108',
        'BJ' => '204',
        'BL' => '652',
        'BM' => '060',
        'BN' => '096',
        'BO' => '068',
        'BQ' => '535',
        'BR' => '076',
        'BS' => '044',
        'BT' => '064',
        'BV' => '074',
        'BW' => '072',
        'BY' => '112',
        'BZ' => '084',
        'CA' => '124',
        'CC' => '166',
        'CD' => '180',
        'CF' => '140',
        'CG' => '178',
        'CH' => '756',
        'CI' => '384',
        'CK' => '184',
        'CL' => '152',
        'CM' => '120',
        'CN' => '156',
        'CO' => '170',
        'CR' => '188',
        'CU' => '192',
        'CV' => '132',
        'CW' => '531',
        'CX' => '162',
        'CY' => '196',
        'CZ' => '203',
        'DE' => '276',
        'DJ' => '262',
        'DK' => '208',
        'DM' => '212',
        'DO' => '214',
        'DZ' => '012',
        'EC' => '218',
        'EE' => '233',
        'EG' => '818',
        'EH' => '732',
        'ER' => '232',
        'ES' => '724',
        'ET' => '231',
        'FI' => '246',
        'FJ' => '242',
        'FK' => '238',
        'FM' => '583',
        'FO' => '234',
        'FR' => '250',
        'GA' => '266',
        'GB' => '826',
        'GD' => '308',
        'GE' => '268',
        'GF' => '254',
        'GG' => '831',
        'GH' => '288',
        'GI' => '292',
        'GL' => '304',
        'GM' => '270',
        'GN' => '324',
        'GP' => '312',
        'GQ' => '226',
        'GR' => '300',
        'GS' => '239',
        'GT' => '320',
        'GU' => '316',
        'GW' => '624',
        'GY' => '328',
        'HK' => '344',
        'HM' => '334',
        'HN' => '340',
        'HR' => '191',
        'HT' => '332',
        'HU' => '348',
        'ID' => '360',
        'IE' => '372',
        'IL' => '376',
        'IM' => '833',
        'IN' => '356',
        'IO' => '086',
        'IQ' => '368',
        'IR' => '364',
        'IS' => '352',
        'IT' => '380',
        'JE' => '832',
        'JM' => '388',
        'JO' => '400',
        'JP' => '392',
        'KE' => '404',
        'KG' => '417',
        'KH' => '116',
        'KI' => '296',
        'KM' => '174',
        'KN' => '659',
        'KP' => '408',
        'KR' => '410',
        'KW' => '414',
        'KY' => '136',
        'KZ' => '398',
        'LA' => '418',
        'LB' => '422',
        'LC' => '662',
        'LI' => '438',
        'LK' => '144',
        'LR' => '430',
        'LS' => '426',
        'LT' => '440',
        'LU' => '442',
        'LV' => '428',
        'LY' => '434',
        'MA' => '504',
        'MC' => '492',
        'MD' => '498',
        'ME' => '499',
        'MF' => '663',
        'MG' => '450',
        'MH' => '584',
        'MK' => '807',
        'ML' => '466',
        'MM' => '104',
        'MN' => '496',
        'MO' => '446',
        'MP' => '580',
        'MQ' => '474',
        'MR' => '478',
        'MS' => '500',
        'MT' => '470',
        'MU' => '480',
        'MV' => '462',
        'MW' => '454',
        'MX' => '484',
        'MY' => '458',
        'MZ' => '508',
        'NA' => '516',
        'NC' => '540',
        'NE' => '562',
        'NF' => '574',
        'NG' => '566',
        'NI' => '558',
        'NL' => '528',
        'NO' => '578',
        'NP' => '524',
        'NR' => '520',
        'NU' => '570',
        'NZ' => '554',
        'OM' => '512',
        'PA' => '591',
        'PE' => '604',
        'PF' => '258',
        'PG' => '598',
        'PH' => '608',
        'PK' => '586',
        'PL' => '616',
        'PM' => '666',
        'PN' => '612',
        'PR' => '630',
        'PS' => '275',
        'PT' => '620',
        'PW' => '585',
        'PY' => '600',
        'QA' => '634',
        'RE' => '638',
        'RO' => '642',
        'RS' => '688',
        'RU' => '643',
        'RW' => '646',
        'SA' => '682',
        'SB' => '090',
        'SC' => '690',
        'SD' => '729',
        'SE' => '752',
        'SG' => '702',
        'SH' => '654',
        'SI' => '705',
        'SJ' => '744',
        'SK' => '703',
        'SL' => '694',
        'SM' => '674',
        'SN' => '686',
        'SO' => '706',
        'SR' => '740',
        'SS' => '728',
        'ST' => '678',
        'SV' => '222',
        'SX' => '534',
        'SY' => '760',
        'SZ' => '748',
        'TC' => '796',
        'TD' => '148',
        'TF' => '260',
        'TG' => '768',
        'TH' => '764',
        'TJ' => '762',
        'TK' => '772',
        'TL' => '626',
        'TM' => '795',
        'TN' => '788',
        'TO' => '776',
        'TR' => '792',
        'TT' => '780',
        'TV' => '798',
        'TW' => '158',
        'TZ' => '834',
        'UA' => '804',
        'UG' => '800',
        'UM' => '581',
        'US' => '840',
        'UY' => '858',
        'UZ' => '860',
        'VA' => '336',
        'VC' => '670',
        'VE' => '862',
        'VG' => '092',
        'VI' => '850',
        'VN' => '704',
        'VU' => '548',
        'WF' => '876',
        'WS' => '882',
        'YE' => '887',
        'YT' => '175',
        'ZA' => '710',
        'ZM' => '894',
        'ZW' => '716',
    ];

    /**
     * Mapping of country international phone prefix
     *
     * @var array
     */
    private static $_more = [
        'AD' => ['name' => 'ANDORRA', 'code' => '376'],
        'AE' => ['name' => 'UNITED ARAB EMIRATES', 'code' => '971'],
        'AF' => ['name' => 'AFGHANISTAN', 'code' => '93'],
        'AG' => ['name' => 'ANTIGUA AND BARBUDA', 'code' => '1268'],
        'AI' => ['name' => 'ANGUILLA', 'code' => '1264'],
        'AL' => ['name' => 'ALBANIA', 'code' => '355'],
        'AM' => ['name' => 'ARMENIA', 'code' => '374'],
        'AN' => ['name' => 'NETHERLANDS ANTILLES', 'code' => '599'],
        'AO' => ['name' => 'ANGOLA', 'code' => '244'],
        'AQ' => ['name' => 'ANTARCTICA', 'code' => '672'],
        'AR' => ['name' => 'ARGENTINA', 'code' => '54'],
        'AS' => ['name' => 'AMERICAN SAMOA', 'code' => '1684'],
        'AT' => ['name' => 'AUSTRIA', 'code' => '43'],
        'AU' => ['name' => 'AUSTRALIA', 'code' => '61'],
        'AW' => ['name' => 'ARUBA', 'code' => '297'],
        'AZ' => ['name' => 'AZERBAIJAN', 'code' => '994'],
        'BA' => ['name' => 'BOSNIA AND HERZEGOVINA', 'code' => '387'],
        'BB' => ['name' => 'BARBADOS', 'code' => '1246'],
        'BD' => ['name' => 'BANGLADESH', 'code' => '880'],
        'BE' => ['name' => 'BELGIUM', 'code' => '32'],
        'BF' => ['name' => 'BURKINA FASO', 'code' => '226'],
        'BG' => ['name' => 'BULGARIA', 'code' => '359'],
        'BH' => ['name' => 'BAHRAIN', 'code' => '973'],
        'BI' => ['name' => 'BURUNDI', 'code' => '257'],
        'BJ' => ['name' => 'BENIN', 'code' => '229'],
        'BL' => ['name' => 'SAINT BARTHELEMY', 'code' => '590'],
        'BM' => ['name' => 'BERMUDA', 'code' => '1441'],
        'BN' => ['name' => 'BRUNEI DARUSSALAM', 'code' => '673'],
        'BO' => ['name' => 'BOLIVIA', 'code' => '591'],
        'BR' => ['name' => 'BRAZIL', 'code' => '55'],
        'BS' => ['name' => 'BAHAMAS', 'code' => '1242'],
        'BT' => ['name' => 'BHUTAN', 'code' => '975'],
        'BW' => ['name' => 'BOTSWANA', 'code' => '267'],
        'BY' => ['name' => 'BELARUS', 'code' => '375'],
        'BZ' => ['name' => 'BELIZE', 'code' => '501'],
        'CA' => ['name' => 'CANADA', 'code' => '1'],
        'CC' => ['name' => 'COCOS (KEELING) ISLANDS', 'code' => '61'],
        'CD' => ['name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'code' => '243'],
        'CF' => ['name' => 'CENTRAL AFRICAN REPUBLIC', 'code' => '236'],
        'CG' => ['name' => 'CONGO', 'code' => '242'],
        'CH' => ['name' => 'SWITZERLAND', 'code' => '41'],
        'CI' => ['name' => 'COTE D IVOIRE', 'code' => '225'],
        'CK' => ['name' => 'COOK ISLANDS', 'code' => '682'],
        'CL' => ['name' => 'CHILE', 'code' => '56'],
        'CM' => ['name' => 'CAMEROON', 'code' => '237'],
        'CN' => ['name' => 'CHINA', 'code' => '86'],
        'CO' => ['name' => 'COLOMBIA', 'code' => '57'],
        'CR' => ['name' => 'COSTA RICA', 'code' => '506'],
        'CU' => ['name' => 'CUBA', 'code' => '53'],
        'CV' => ['name' => 'CAPE VERDE', 'code' => '238'],
        'CX' => ['name' => 'CHRISTMAS ISLAND', 'code' => '61'],
        'CY' => ['name' => 'CYPRUS', 'code' => '357'],
        'CZ' => ['name' => 'CZECH REPUBLIC', 'code' => '420'],
        'DE' => ['name' => 'GERMANY', 'code' => '49'],
        'DJ' => ['name' => 'DJIBOUTI', 'code' => '253'],
        'DK' => ['name' => 'DENMARK', 'code' => '45'],
        'DM' => ['name' => 'DOMINICA', 'code' => '1767'],
        'DO' => ['name' => 'DOMINICAN REPUBLIC', 'code' => '1809'],
        'DZ' => ['name' => 'ALGERIA', 'code' => '213'],
        'EC' => ['name' => 'ECUADOR', 'code' => '593'],
        'EE' => ['name' => 'ESTONIA', 'code' => '372'],
        'EG' => ['name' => 'EGYPT', 'code' => '20'],
        'ER' => ['name' => 'ERITREA', 'code' => '291'],
        'ES' => ['name' => 'SPAIN', 'code' => '34'],
        'ET' => ['name' => 'ETHIOPIA', 'code' => '251'],
        'FI' => ['name' => 'FINLAND', 'code' => '358'],
        'FJ' => ['name' => 'FIJI', 'code' => '679'],
        'FK' => ['name' => 'FALKLAND ISLANDS (MALVINAS)', 'code' => '500'],
        'FM' => ['name' => 'MICRONESIA, FEDERATED STATES OF', 'code' => '691'],
        'FO' => ['name' => 'FAROE ISLANDS', 'code' => '298'],
        'FR' => ['name' => 'FRANCE', 'code' => '33'],
        'GA' => ['name' => 'GABON', 'code' => '241'],
        'GB' => ['name' => 'UNITED KINGDOM', 'code' => '44'],
        'GD' => ['name' => 'GRENADA', 'code' => '1473'],
        'GE' => ['name' => 'GEORGIA', 'code' => '995'],
        'GH' => ['name' => 'GHANA', 'code' => '233'],
        'GI' => ['name' => 'GIBRALTAR', 'code' => '350'],
        'GL' => ['name' => 'GREENLAND', 'code' => '299'],
        'GM' => ['name' => 'GAMBIA', 'code' => '220'],
        'GN' => ['name' => 'GUINEA', 'code' => '224'],
        'GQ' => ['name' => 'EQUATORIAL GUINEA', 'code' => '240'],
        'GR' => ['name' => 'GREECE', 'code' => '30'],
        'GT' => ['name' => 'GUATEMALA', 'code' => '502'],
        'GU' => ['name' => 'GUAM', 'code' => '1671'],
        'GW' => ['name' => 'GUINEA-BISSAU', 'code' => '245'],
        'GY' => ['name' => 'GUYANA', 'code' => '592'],
        'HK' => ['name' => 'HONG KONG', 'code' => '852'],
        'HN' => ['name' => 'HONDURAS', 'code' => '504'],
        'HR' => ['name' => 'CROATIA', 'code' => '385'],
        'HT' => ['name' => 'HAITI', 'code' => '509'],
        'HU' => ['name' => 'HUNGARY', 'code' => '36'],
        'ID' => ['name' => 'INDONESIA', 'code' => '62'],
        'IE' => ['name' => 'IRELAND', 'code' => '353'],
        'IL' => ['name' => 'ISRAEL', 'code' => '972'],
        'IM' => ['name' => 'ISLE OF MAN', 'code' => '44'],
        'IN' => ['name' => 'INDIA', 'code' => '91'],
        'IQ' => ['name' => 'IRAQ', 'code' => '964'],
        'IR' => ['name' => 'IRAN, ISLAMIC REPUBLIC OF', 'code' => '98'],
        'IS' => ['name' => 'ICELAND', 'code' => '354'],
        'IT' => ['name' => 'ITALY', 'code' => '39'],
        'JM' => ['name' => 'JAMAICA', 'code' => '1876'],
        'JO' => ['name' => 'JORDAN', 'code' => '962'],
        'JP' => ['name' => 'JAPAN', 'code' => '81'],
        'KE' => ['name' => 'KENYA', 'code' => '254'],
        'KG' => ['name' => 'KYRGYZSTAN', 'code' => '996'],
        'KH' => ['name' => 'CAMBODIA', 'code' => '855'],
        'KI' => ['name' => 'KIRIBATI', 'code' => '686'],
        'KM' => ['name' => 'COMOROS', 'code' => '269'],
        'KN' => ['name' => 'SAINT KITTS AND NEVIS', 'code' => '1869'],
        'KP' => ['name' => 'KOREA DEMOCRATIC PEOPLES REPUBLIC OF', 'code' => '850'],
        'KR' => ['name' => 'KOREA REPUBLIC OF', 'code' => '82'],
        'KW' => ['name' => 'KUWAIT', 'code' => '965'],
        'KY' => ['name' => 'CAYMAN ISLANDS', 'code' => '1345'],
        'KZ' => ['name' => 'KAZAKSTAN', 'code' => '7'],
        'LA' => ['name' => 'LAO PEOPLES DEMOCRATIC REPUBLIC', 'code' => '856'],
        'LB' => ['name' => 'LEBANON', 'code' => '961'],
        'LC' => ['name' => 'SAINT LUCIA', 'code' => '1758'],
        'LI' => ['name' => 'LIECHTENSTEIN', 'code' => '423'],
        'LK' => ['name' => 'SRI LANKA', 'code' => '94'],
        'LR' => ['name' => 'LIBERIA', 'code' => '231'],
        'LS' => ['name' => 'LESOTHO', 'code' => '266'],
        'LT' => ['name' => 'LITHUANIA', 'code' => '370'],
        'LU' => ['name' => 'LUXEMBOURG', 'code' => '352'],
        'LV' => ['name' => 'LATVIA', 'code' => '371'],
        'LY' => ['name' => 'LIBYAN ARAB JAMAHIRIYA', 'code' => '218'],
        'MA' => ['name' => 'MOROCCO', 'code' => '212'],
        'MC' => ['name' => 'MONACO', 'code' => '377'],
        'MD' => ['name' => 'MOLDOVA, REPUBLIC OF', 'code' => '373'],
        'ME' => ['name' => 'MONTENEGRO', 'code' => '382'],
        'MF' => ['name' => 'SAINT MARTIN', 'code' => '1599'],
        'MG' => ['name' => 'MADAGASCAR', 'code' => '261'],
        'MH' => ['name' => 'MARSHALL ISLANDS', 'code' => '692'],
        'MK' => ['name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'code' => '389'],
        'ML' => ['name' => 'MALI', 'code' => '223'],
        'MM' => ['name' => 'MYANMAR', 'code' => '95'],
        'MN' => ['name' => 'MONGOLIA', 'code' => '976'],
        'MO' => ['name' => 'MACAU', 'code' => '853'],
        'MP' => ['name' => 'NORTHERN MARIANA ISLANDS', 'code' => '1670'],
        'MR' => ['name' => 'MAURITANIA', 'code' => '222'],
        'MS' => ['name' => 'MONTSERRAT', 'code' => '1664'],
        'MT' => ['name' => 'MALTA', 'code' => '356'],
        'MU' => ['name' => 'MAURITIUS', 'code' => '230'],
        'MV' => ['name' => 'MALDIVES', 'code' => '960'],
        'MW' => ['name' => 'MALAWI', 'code' => '265'],
        'MX' => ['name' => 'MEXICO', 'code' => '52'],
        'MY' => ['name' => 'MALAYSIA', 'code' => '60'],
        'MZ' => ['name' => 'MOZAMBIQUE', 'code' => '258'],
        'NA' => ['name' => 'NAMIBIA', 'code' => '264'],
        'NC' => ['name' => 'NEW CALEDONIA', 'code' => '687'],
        'NE' => ['name' => 'NIGER', 'code' => '227'],
        'NG' => ['name' => 'NIGERIA', 'code' => '234'],
        'NI' => ['name' => 'NICARAGUA', 'code' => '505'],
        'NL' => ['name' => 'NETHERLANDS', 'code' => '31'],
        'NO' => ['name' => 'NORWAY', 'code' => '47'],
        'NP' => ['name' => 'NEPAL', 'code' => '977'],
        'NR' => ['name' => 'NAURU', 'code' => '674'],
        'NU' => ['name' => 'NIUE', 'code' => '683'],
        'NZ' => ['name' => 'NEW ZEALAND', 'code' => '64'],
        'OM' => ['name' => 'OMAN', 'code' => '968'],
        'PA' => ['name' => 'PANAMA', 'code' => '507'],
        'PE' => ['name' => 'PERU', 'code' => '51'],
        'PF' => ['name' => 'FRENCH POLYNESIA', 'code' => '689'],
        'PG' => ['name' => 'PAPUA NEW GUINEA', 'code' => '675'],
        'PH' => ['name' => 'PHILIPPINES', 'code' => '63'],
        'PK' => ['name' => 'PAKISTAN', 'code' => '92'],
        'PL' => ['name' => 'POLAND', 'code' => '48'],
        'PM' => ['name' => 'SAINT PIERRE AND MIQUELON', 'code' => '508'],
        'PN' => ['name' => 'PITCAIRN', 'code' => '870'],
        'PR' => ['name' => 'PUERTO RICO', 'code' => '1'],
        'PT' => ['name' => 'PORTUGAL', 'code' => '351'],
        'PW' => ['name' => 'PALAU', 'code' => '680'],
        'PY' => ['name' => 'PARAGUAY', 'code' => '595'],
        'QA' => ['name' => 'QATAR', 'code' => '974'],
        'RE' => ['name' => 'REUNION', 'code' => '262'],
        'RO' => ['name' => 'ROMANIA', 'code' => '40'],
        'RS' => ['name' => 'SERBIA', 'code' => '381'],
        'RU' => ['name' => 'RUSSIAN FEDERATION', 'code' => '7'],
        'RW' => ['name' => 'RWANDA', 'code' => '250'],
        'SA' => ['name' => 'SAUDI ARABIA', 'code' => '966'],
        'SB' => ['name' => 'SOLOMON ISLANDS', 'code' => '677'],
        'SC' => ['name' => 'SEYCHELLES', 'code' => '248'],
        'SD' => ['name' => 'SUDAN', 'code' => '249'],
        'SE' => ['name' => 'SWEDEN', 'code' => '46'],
        'SG' => ['name' => 'SINGAPORE', 'code' => '65'],
        'SH' => ['name' => 'SAINT HELENA', 'code' => '290'],
        'SI' => ['name' => 'SLOVENIA', 'code' => '386'],
        'SK' => ['name' => 'SLOVAKIA', 'code' => '421'],
        'SL' => ['name' => 'SIERRA LEONE', 'code' => '232'],
        'SM' => ['name' => 'SAN MARINO', 'code' => '378'],
        'SN' => ['name' => 'SENEGAL', 'code' => '221'],
        'SO' => ['name' => 'SOMALIA', 'code' => '252'],
        'SR' => ['name' => 'SURINAME', 'code' => '597'],
        'ST' => ['name' => 'SAO TOME AND PRINCIPE', 'code' => '239'],
        'SV' => ['name' => 'EL SALVADOR', 'code' => '503'],
        'SY' => ['name' => 'SYRIAN ARAB REPUBLIC', 'code' => '963'],
        'SZ' => ['name' => 'SWAZILAND', 'code' => '268'],
        'TC' => ['name' => 'TURKS AND CAICOS ISLANDS', 'code' => '1649'],
        'TD' => ['name' => 'CHAD', 'code' => '235'],
        'TG' => ['name' => 'TOGO', 'code' => '228'],
        'TH' => ['name' => 'THAILAND', 'code' => '66'],
        'TJ' => ['name' => 'TAJIKISTAN', 'code' => '992'],
        'TK' => ['name' => 'TOKELAU', 'code' => '690'],
        'TL' => ['name' => 'TIMOR-LESTE', 'code' => '670'],
        'TM' => ['name' => 'TURKMENISTAN', 'code' => '993'],
        'TN' => ['name' => 'TUNISIA', 'code' => '216'],
        'TO' => ['name' => 'TONGA', 'code' => '676'],
        'TR' => ['name' => 'TURKEY', 'code' => '90'],
        'TT' => ['name' => 'TRINIDAD AND TOBAGO', 'code' => '1868'],
        'TV' => ['name' => 'TUVALU', 'code' => '688'],
        'TW' => ['name' => 'TAIWAN, PROVINCE OF CHINA', 'code' => '886'],
        'TZ' => ['name' => 'TANZANIA, UNITED REPUBLIC OF', 'code' => '255'],
        'UA' => ['name' => 'UKRAINE', 'code' => '380'],
        'UG' => ['name' => 'UGANDA', 'code' => '256'],
        'US' => ['name' => 'UNITED STATES', 'code' => '1'],
        'UY' => ['name' => 'URUGUAY', 'code' => '598'],
        'UZ' => ['name' => 'UZBEKISTAN', 'code' => '998'],
        'VA' => ['name' => 'HOLY SEE (VATICAN CITY STATE)', 'code' => '39'],
        'VC' => ['name' => 'SAINT VINCENT AND THE GRENADINES', 'code' => '1784'],
        'VE' => ['name' => 'VENEZUELA', 'code' => '58'],
        'VG' => ['name' => 'VIRGIN ISLANDS, BRITISH', 'code' => '1284'],
        'VI' => ['name' => 'VIRGIN ISLANDS, U.S.', 'code' => '1340'],
        'VN' => ['name' => 'VIET NAM', 'code' => '84'],
        'VU' => ['name' => 'VANUATU', 'code' => '678'],
        'WF' => ['name' => 'WALLIS AND FUTUNA', 'code' => '681'],
        'WS' => ['name' => 'SAMOA', 'code' => '685'],
        'XK' => ['name' => 'KOSOVO', 'code' => '381'],
        'YE' => ['name' => 'YEMEN', 'code' => '967'],
        'YT' => ['name' => 'MAYOTTE', 'code' => '262'],
        'ZA' => ['name' => 'SOUTH AFRICA', 'code' => '27'],
        'ZM' => ['name' => 'ZAMBIA', 'code' => '260'],
        'ZW' => ['name' => 'ZIMBABWE', 'code' => '263'],
    ];

    /**
     * Retrieve corresponding numeric country code (ISO 3166)
     *
     * @param string $isoCode
     * @param string $default
     * @return string|null
     */
    public static function getNumericCode($isoCode, $default = null)
    {
        if (isset(self::$_mapping[$isoCode])) {
            return self::$_mapping[$isoCode];
        }

        return $default;
    }

    /**
     * Retrieve corresponding international phone code
     *
     * @param string $isoCode
     * @param string $default
     * @return string|null
     */
    public static function getPhoneCode($isoCode, $default = null)
    {
        if (isset(self::$_more[$isoCode])) {
            return '+' . self::$_more[$isoCode]['code'];
        }

        return $default;
    }
}
